// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdJ42xB_lKOCuiW-ZnnQwTXuywb7OJAY',
    appId: '1:1081660599052:web:0615c2ec33239d82aaf729',
    messagingSenderId: '1081660599052',
    projectId: 'instabuy-app-5bfcb',
    authDomain: 'instabuy-app-5bfcb.firebaseapp.com',
    storageBucket: 'instabuy-app-5bfcb.firebasestorage.app',
    measurementId: 'G-0R233MVQCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6YMXr1AQLvyEh4QCF4uwoa6p0ZvZXGk',
    appId: '1:1081660599052:android:0ce96998a4b355f7aaf729',
    messagingSenderId: '1081660599052',
    projectId: 'instabuy-app-5bfcb',
    storageBucket: 'instabuy-app-5bfcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk86h1eCS5A2cHR9A6-vjrunX0CLYBqCo',
    appId: '1:1081660599052:ios:5a02ae7c11d11c1caaf729',
    messagingSenderId: '1081660599052',
    projectId: 'instabuy-app-5bfcb',
    storageBucket: 'instabuy-app-5bfcb.firebasestorage.app',
    iosBundleId: 'com.example.instaBuyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk86h1eCS5A2cHR9A6-vjrunX0CLYBqCo',
    appId: '1:1081660599052:ios:5a02ae7c11d11c1caaf729',
    messagingSenderId: '1081660599052',
    projectId: 'instabuy-app-5bfcb',
    storageBucket: 'instabuy-app-5bfcb.firebasestorage.app',
    iosBundleId: 'com.example.instaBuyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcdJ42xB_lKOCuiW-ZnnQwTXuywb7OJAY',
    appId: '1:1081660599052:web:3c636debca02042eaaf729',
    messagingSenderId: '1081660599052',
    projectId: 'instabuy-app-5bfcb',
    authDomain: 'instabuy-app-5bfcb.firebaseapp.com',
    storageBucket: 'instabuy-app-5bfcb.firebasestorage.app',
    measurementId: 'G-H461J3LKQP',
  );
}
